### ISSUE TITLE
Hi Galvin! 

### ISSUE THREAD

**Issue by flandia** [GalvinGao/GalvinGao#1]
Hi Galvin! I found something interesting commented out in your README.md! As you mentioned, I was trying to follow your social accounts, however I found none of them :'( So... why not start by following Github account? (I've already followed yours 😆)

btw im also a fan of miku XDDDDDDDDDDDDD

**Comment by GalvinGao** [comment]
Eyyyy Hi there! So glad to see someone that found the easter egg I've left :D

Oh and you can follow my Twitter at https://twitter.com/GalvinGaoLucky, although to be honest I don't really post things frequently lol. You could also add me on Discord as `GalvinGao#1176` :D

And I've followed you back on GitHub!

Thanks for participating in my easter egg lol :D

**Comment by flandia** [comment]
Hey Galvin!

I didn't follow you on Twitter since I don't use it. However I added you on Discord as `Flandia_Yingman#9564`, same as my Github username (just to let you know that's me).

Your easter egg is fascinating and I really enjoy it! XDD

**Comment by flandia** [comment]
Hey there! 

I'm currently developing a website called [ArkWaifu](https://github.com/FlandiaYingman/arkwaifu) for practicing my web development skills. It would categorize the art resources from Arknights and show them out.

Now I've completed the backend part and beginning to do the frontend part. However I'm new to frontends. I almost drown in those various frameworks (Vue, React etc.) and UI design systems (Material UI, antd etc.). 

So I'm wondering which of them you would suggest beginners to use (or, which one do you like most / use most)? Any suggestions would help! Thaaaaanks 🎉 :D

**Comment by GalvinGao** [comment]
> Hey there!
> 
> I'm currently developing a website called [ArkWaifu](https://github.com/FlandiaYingman/arkwaifu) for practicing my web development skills. It would categorize the art resources from Arknights and show them out.
> 
> Now I've completed the backend part and beginning to do the frontend part. However I'm new to frontends. I almost drown in those various frameworks (Vue, React etc.) and UI design systems (Material UI, antd etc.).
> 
> So I'm wondering which of them you would suggest beginners to use (or, which one do you like most / use most)? Any suggestions would help! Thaaaaanks 🎉 :D

Ahhh sounds awesome! I started with web development with "vanilla", so it was like pure HTML and CSS and JS handcrafted bit by bit and it was awful. Then I started to use Vue.js (vuejs.org) which is pretty easy to get started with and an awesome framework. I found it is a great starting point so I would highly recommend so if you want to use a framework. Personally, I don't recommend starting with React as a beginner as there's pitfalls and conventions that are not so obvious and easy to follow with, however once you've mastered the basics React could be really powerful as a web framework.

For UI framework, personally my favorite is VuetifyJS which implements Google's Material Design and in my opinion the best framework implementation out there for Material Design. There's also other awesome UI frameworks that gained a lot of popularity, e.g. Bootstrap, Element-UI, Ant Design and more. I would recommend you check out the [Awesome Vue](https://github.com/vuejs/awesome-vue) repo for a curated list of elements in the Vue ecosystem.

The last key part I would say is to practice more, especially at beginning, and my way of learning a new language is to actually get hands dirty on projects. Don't afraid your code is messy - everyone starts from that, just go for it. And once you started to notice you are asking yourself questions like "hey, maybe there's a better solution for this?", your code readability would become better :D 

Wish you the best luck to be an awesome WebD Developer! 🍻

**Comment by flandia** [comment]
All day yesterday I'd been trying out both Vue and React. Eventually I chose Vue (with Vuetify) as you suggested. Since Vuetify does not support Vue 3, I decided to use Vue 2. I didn't see a lot of differences, so I planned to try Vue 2 first and to migrate to Vue 3 when Vuetify supports it (or, switching to React?).

I find React works more like writing HTML inside of JavaScript (JSX) and Vue works oppositely - writing JavaScript inside of HTML (the directives). Though I feel kind with React since I'm more familiar with JavaScript than the markup things, I think Vue is much easier. I could build a running website quite easy just like building Lego toys (yeah I copy/pasted 10 times the element instead of using `v-for`).

And it just worked like magic! 

![localhost_8080_avgs_mainline](https://user-images.githubusercontent.com/9929037/155111244-5d2c99e0-7122-40da-baa3-4fa6efc6292f.png)

![localhost_8080_all](https://user-images.githubusercontent.com/9929037/155111249-9867b556-43f8-465d-b8d3-29958746966d.png)

Next I'm trying to beautify the UI... Would you suggest some articles or guides to read? ...How about the material design guides (https://material.io/design)?

Hooray!

**Comment by GalvinGao** [comment]
> All day yesterday I'd been trying out both Vue and React. Eventually I chose Vue (with Vuetify) as you suggested. Since Vuetify does not support Vue 3, I decided to use Vue 2. I didn't see a lot of differences, so I planned to try Vue 2 first and to migrate to Vue 3 when Vuetify supports it (or, switching to React?).
> 
> I find React works more like writing HTML inside of JavaScript (JSX) and Vue works oppositely - writing JavaScript inside of HTML (the directives). Though I feel kind with React since I'm more familiar with JavaScript than the markup things, I think Vue is much easier. I could build a running website quite easy just like building Lego toys (yeah I copy/pasted 10 times the element instead of using `v-for`).
> 
> And it just worked like magic!
> 
> ![localhost_8080_avgs_mainline](https://user-images.githubusercontent.com/9929037/155111244-5d2c99e0-7122-40da-baa3-4fa6efc6292f.png)
> 
> ![localhost_8080_all](https://user-images.githubusercontent.com/9929037/155111249-9867b556-43f8-465d-b8d3-29958746966d.png)
> 
> Next I'm trying to beautify the UI... Would you suggest some articles or guides to read? ...How about the material design guides ([material.io/design](https://material.io/design))?
> 
> Hooray!

eyyyy nice! React definitely feels more natural with JSX. From my own perspective if you find natural with React, wrap the current vue project and go for it! Try with different things and digest those as your own experience would be the key part for the whole idea of learning a new language :D

Keep me posted on how things goes! The ArkWaifu project looks gorgeous and could be a really nice place to explore those image assets!

**Comment by flandia** [comment]
Most of these days I'd been working with containerizing the app and configuring the production environments such as Nginx and Postgres. There were some problems like, psql refused the connection from Docker container, I had to edit `pg_hba.conf` to make it work; the app behaved differently between on Win and on Linux - I eventually found the problem was caused by file name case sensivity; gofiber/fiber crashed the app when user requested, that was caused by a valyala/fasthttp bug.

Finally after experiencing all those issues and bugs, the first release-candidate version of ArkWaifu went live today at 1:00 AM. Then the first production release went live just now. Though it is buggy, simple and crude, I believe it is a good beginning.

The living website of ArkWaifu can be found at http://arkwaifu.anagke.top/ (I'm preparing a new domain with certs so this is temporary), and the repo is at https://github.com/FlandiaYingman/arkwaifu/. 🎉 

You helped me a lot with the development. Thanks! XDDDD


![arkwaifu anagke top_avgs_stories_act11d0_level_act11d0_04_beg](https://user-images.githubusercontent.com/9929037/156878344-7f07e0e6-34ec-4241-bc86-0493a78e6e44.png)

**Comment by flandia** [comment]
Heeey GG! 

Arknights is going to update tomorrow (UTC+8 March 15th) in CN server. During the maintainance period, Arkwaifu shall update the assets by itself, and, it is Arkwaifu's first time!

Arkwaifu will check for the updates periodically (every 5 mins). Once updated, Arkwaifu will fill its database with new assets. This process shall take up to 5 mins, but it normally takes only ~1 min. Though Arkwaifu is behind a CDN, the metadata of assets are not cached. So we would probably see new assets right after they have been updated.

Hmm... If everything goes right, we'll see the assets for the new event tomorrow between 10:00 AM and 4:00 PM. Since I'm not sure whether the CDN caching will work every place in the world as I expected, so, would you like to check it with me? If yes, just visit https://arkwaifu.cc/ anytime and tell me what's happening.

**Comment by GalvinGao** [comment]
> Heeey GG! 
> 
> 
> 
> Arknights is going to update tomorrow (UTC+8 March 15th) in CN server. During the maintainance period, Arkwaifu shall update the assets by itself, and, it is Arkwaifu's first time!
> 
> 
> 
> Arkwaifu will check for the updates periodically (every 5 mins). Once updated, Arkwaifu will fill its database with new assets. This process shall take up to 5 mins, but it normally takes only ~1 min. Though Arkwaifu is behind a CDN, the metadata of assets are not cached. So we would probably see new assets right after they have been updated.
> 
> 
> 
> Hmm... If everything goes right, we'll see the assets for the new event tomorrow between 10:00 AM and 4:00 PM. Since I'm not sure whether the CDN caching will work every place in the world as I expected, so, would you like to check it with me? If yes, just visit https://arkwaifu.cc/ anytime and tell me what's happening.

eyyy that looks awesome! Definitely going to try that tomorrow!

**Comment by GalvinGao** [comment]
> Heeey GG! 
> 
> 
> 
> Arknights is going to update tomorrow (UTC+8 March 15th) in CN server. During the maintainance period, Arkwaifu shall update the assets by itself, and, it is Arkwaifu's first time!
> 
> 
> 
> Arkwaifu will check for the updates periodically (every 5 mins). Once updated, Arkwaifu will fill its database with new assets. This process shall take up to 5 mins, but it normally takes only ~1 min. Though Arkwaifu is behind a CDN, the metadata of assets are not cached. So we would probably see new assets right after they have been updated.
> 
> 
> 
> Hmm... If everything goes right, we'll see the assets for the new event tomorrow between 10:00 AM and 4:00 PM. Since I'm not sure whether the CDN caching will work every place in the world as I expected, so, would you like to check it with me? If yes, just visit https://arkwaifu.cc/ anytime and tell me what's happening.

And for how it's working, I'm currently in Beijing and via both China Unicom Broadband & Cellular it works all fine.

**Comment by flandia** [comment]
Close because we could use IM now. :D
